/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package adminstrator.view;

import java.text.SimpleDateFormat;

/**
 *
 * @author DELL
 */
public class InforEmployee extends javax.swing.JDialog {
    private HomeForm hf;
    SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form InforEmployee
     */
    public InforEmployee(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        hf = (HomeForm) parent;
        lableTK.setText(hf.getE().getNameTK());
        lableName.setText(hf.getE().getName());
        lableGender.setText(hf.getE().getGender());
        lableBirth.setText(df.format(hf.getE().getDob()));
        lableAddress.setText(hf.getE().getAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lableName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lableBirth = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lableGender = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lableTK = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lableAddress = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_11Ảnh-đại-diện-fb-mặc-định-nữ-150x150.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 90, 130));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Họ Và Tên:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 30));

        lableName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lableName.setText("*Tên");
        getContentPane().add(lableName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 230, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Ngày Sinh:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        lableBirth.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lableBirth.setText("*Ngày Sinh");
        getContentPane().add(lableBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 190, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("giới Tính:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        lableGender.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lableGender.setText("*Gioi tính");
        getContentPane().add(lableGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 190, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Tài Khoản:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        lableTK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lableTK.setText("*tài Khoản");
        getContentPane().add(lableTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 190, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Địa chỉ:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        lableAddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lableAddress.setText("*Địa chỉ");
        getContentPane().add(lableAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 180, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rsz_inforadmin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InforEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InforEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InforEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InforEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InforEmployee dialog = new InforEmployee(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lableAddress;
    private javax.swing.JLabel lableBirth;
    private javax.swing.JLabel lableGender;
    private javax.swing.JLabel lableName;
    private javax.swing.JLabel lableTK;
    // End of variables declaration//GEN-END:variables
}
